defaults:
  - base
  - _self_

max_epochs: 500
batch_size: 16
learning_rate: 1e-4
dataset: PascalSegmentation
class_hint: true
drop_out_rate: 0.1

gpus: [2]
log_dir: ./logs/PascalSegmentation
logger_freq: 200
