defaults:
  - base
  - _self_

max_epochs: 200
batch_size: 16
learning_rate: 1e-4
dataset: PascalScribble
split_path: ./SSL_splits/1_8/labeled.txt
class_hint: true
drop_out_rate: 0.0

resume_path: ./logs/PascalScribble/lightning_logs/uncond_16/checkpoints/epoch=199-step=44199.ckpt
resume_init_only: True

gpus: [3]
log_dir: ./logs/PascalScribble
logger_freq: 200
