defaults:
  - base
  - _self_

max_epochs: 200
batch_size: 16
learning_rate: 1e-4
dataset: PascalScribble
class_hint: true
drop_out_rate: 0.1
drop_out_text: a high-quality, detailed, and professional image

gpus: [2]
log_dir: ./logs/PascalScribble
logger_freq: 200
